// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240312161155_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bundás Kenyér bundából és kenyérből van",
                            Name = "Bundás Kenyér",
                            Price = 2000
                        },
                        new
                        {
                            Id = 2,
                            Description = "Omlett 3 tojásból készül és nagyon fincsa",
                            Name = "Omlett",
                            Price = 1800
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tükörtojás 3 tojásból készül és nagyon fincsa",
                            Name = "Tükörtojás",
                            Price = 1800
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ez az étel, jó, de nem mindenki szereti",
                            Name = "Sült Oldalas",
                            Price = 2800
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sima szendvics... semmi extra, kenyér, vaj, cuccok",
                            Name = "Szendvics",
                            Price = 1200
                        },
                        new
                        {
                            Id = 6,
                            Description = "Legjobb házi krumpliból, friss olajban sülve",
                            Name = "Sültkrumpli",
                            Price = 1000
                        },
                        new
                        {
                            Id = 7,
                            Description = "Frissen készült humusz, zöldségekkel",
                            Name = "Humusz tál",
                            Price = 1200
                        },
                        new
                        {
                            Id = 8,
                            Description = "Olasz módra készült, legfinomabb tésztaétel",
                            Name = "Bolognai Spagetti",
                            Price = 2900
                        },
                        new
                        {
                            Id = 9,
                            Description = "Frissen vágott zöldségekből, uborka, paaradicsom, saláta, és egy kis szeretet",
                            Name = "Saláta",
                            Price = 1000
                        });
                });

            modelBuilder.Entity("Domain.Models.MealRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("RestrictionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("RestrictionId");

                    b.ToTable("MealRestrictions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealId = 1,
                            RestrictionId = 2
                        },
                        new
                        {
                            Id = 2,
                            MealId = 1,
                            RestrictionId = 3
                        },
                        new
                        {
                            Id = 3,
                            MealId = 2,
                            RestrictionId = 2
                        });
                });

            modelBuilder.Entity("Domain.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("Domain.Models.Restriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restrictions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gluténmentes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vegetáriánus"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laktózmentes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vegán"
                        });
                });

            modelBuilder.Entity("Domain.Models.Topping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topping");
                });

            modelBuilder.Entity("PizzaTopping", b =>
                {
                    b.Property<int>("PizzasId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingsId")
                        .HasColumnType("int");

                    b.HasKey("PizzasId", "ToppingsId");

                    b.HasIndex("ToppingsId");

                    b.ToTable("PizzaTopping");
                });

            modelBuilder.Entity("RestrictionTopping", b =>
                {
                    b.Property<int>("RestrictionsId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingsId")
                        .HasColumnType("int");

                    b.HasKey("RestrictionsId", "ToppingsId");

                    b.HasIndex("ToppingsId");

                    b.ToTable("RestrictionTopping");
                });

            modelBuilder.Entity("Domain.Models.MealRestriction", b =>
                {
                    b.HasOne("Domain.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Restriction", "Restriction")
                        .WithMany()
                        .HasForeignKey("RestrictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Restriction");
                });

            modelBuilder.Entity("PizzaTopping", b =>
                {
                    b.HasOne("Domain.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestrictionTopping", b =>
                {
                    b.HasOne("Domain.Models.Restriction", null)
                        .WithMany()
                        .HasForeignKey("RestrictionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Topping", null)
                        .WithMany()
                        .HasForeignKey("ToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
